// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfqaaewsnqveshupijeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmcWFhZXdzbnF2ZXNodXBpamVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjA0NzgsImV4cCI6MjA2NzAzNjQ3OH0.g6V1aKLqSgo547xKPsP4fCmi4gIPMcRABtiurDBOYvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});